/**
 * Page exports
 * All page components in one place for easy importing
 */

export { Dashboard } from './Dashboard';
export { Profile } from './Profile';
export { Settings } from './Settings';
export { Components } from './Components';
export { LearningPaths } from './LearningPaths';
export { LearningPathDetail } from './LearningPathDetail';
export { Positionnement } from './Positionnement';
export { Recherche } from './Recherche';
export { Billing } from './Billing';
export { SubscriptionPayment } from './SubscriptionPayment';
export { VerifyEmail } from './VerifyEmail';
export { MagicLink } from './MagicLink';
export { Coaching } from './Coaching';
export { Collaboration } from './Collaboration';
export { PagesIndex } from './PagesIndex';
export { Login } from './Login';
export { Signup } from './Signup';
export { ForgotPassword } from './ForgotPassword';
export { Notifications } from './Notifications';
export { Messages } from './Messages';
export { Leaderboard } from './Leaderboard';
export { Veille } from './Veille';
export { VeilleActus } from './VeilleActus';
export { VeilleTutoriels } from './VeilleTutoriels';
export { VeilleDossiers } from './VeilleDossiers';
export { Journal } from './Journal';
export { VeilleContent } from './VeilleContent';
export { ArticleDetail } from './ArticleDetail';
export { Dossier } from './Dossier';
export { VideoTutorial } from './VideoTutorial';
export { VideoReels } from './VideoReels';
export { Magazine } from './Magazine';
export { MagazineArticle } from './MagazineArticle';
export { WeeklyNewsletter } from './WeeklyNewsletter';
export { WeeklyNewsDetail } from './WeeklyNewsDetail';
export { Newsletter } from './Newsletter';
export { Project } from './Project';
export { LearningSpace } from './LearningSpace';
export { Onboarding } from './Onboarding';
export { CoachingBookingFlow } from './CoachingBookingFlow';
export { PreCoachingQuestionnaire } from './PreCoachingQuestionnaire';
export { PreCoachingQuestionnaireResponse } from './PreCoachingQuestionnaireResponse';
export { JournalDetail } from './JournalDetail';
export { JournalNewEntry } from './JournalNewEntry';
export { JournalFreeEntry } from './JournalFreeEntry';
export { ResetPassword } from './ResetPassword';
export { Account } from './Account';
export { Error404 } from './Error404';
export { Error500 } from './Error500';
export { Help } from './Help';
export { Enterprise } from './Enterprise';
export { CourseDetail } from './CourseDetail';
export { LessonPlayer } from './LessonPlayer';
export { AstucesViewer } from './AstucesViewer';
export { ComplementaryContentViewer } from './ComplementaryContentViewer';
export { FlashcardsViewer } from './FlashcardsViewer';
export { VideoViewer } from './VideoViewer';
export { CoachingCompteRendu } from './CoachingCompteRendu';
// Phase 11 — Sitemap Alignment & MVP
export { default as Passeport } from './Passeport';
export { default as Gamification } from './Gamification';
export { default as CoachDashboard } from './CoachDashboard';
export { default as ManagerEnterprise } from './ManagerEnterprise';
export { default as ManagerCohort } from './ManagerCohort';
// Phase 12 — MVP P0 pages
export { default as PasseportCompetenceDetail } from './PasseportCompetenceDetail';
export { default as PasseportObjectifs } from './PasseportObjectifs';
export { default as CoachHeatmap } from './CoachHeatmap';
export { default as OnboardingSuccess } from './OnboardingSuccess';
export { default as OnboardingTutorial } from './OnboardingTutorial';
export { default as CoachingSessionDetail } from './CoachingSessionDetail';
export { default as CoachingCorrections } from './CoachingCorrections';
export { default as CoachCorrectionsQueue } from './CoachCorrectionsQueue';
export { default as CoachCorrectionInterface } from './CoachCorrectionInterface';
export { default as CoachApprenants } from './CoachApprenants';
export { default as BadgeDetail } from './BadgeDetail';
export { default as ProfileBadgesCompetences } from './ProfileBadgesCompetences';
export { default as ManagerAlerts } from './ManagerAlerts';
export { default as ManagerExport } from './ManagerExport';
export { default as DashboardCompetenceDetail } from './DashboardCompetenceDetail';
export { default as CoachTeamDashboard } from './CoachTeamDashboard';
export { default as FicheApprenantAnalytics } from './FicheApprenantAnalytics';
export { default as ProfilePrivacy } from './ProfilePrivacy';
export { default as EnterpriseAnalyticsDashboard } from './EnterpriseAnalyticsDashboard';
// Phase 13 — Remaining MVP P0 pages
export { default as PasseportRoadmap } from './PasseportRoadmap';
export { default as PasseportJac } from './PasseportJac';
export { default as CoachAnalytics } from './CoachAnalytics';
export { default as EnterpriseKpis } from './EnterpriseKpis';
export { default as ProfileConsent } from './ProfileConsent';
export { default as AlerteInactivite } from './AlerteInactivite';
export { default as AlerteStagnation } from './AlerteStagnation';
