/**
 * Page exports
 * All page components in one place for easy importing
 */

export { Dashboard } from './Dashboard';
export { Profile } from './Profile';
export { Settings } from './Settings';
export { Components } from './Components';
export { LearningPaths } from './LearningPaths';
export { LearningPathDetail } from './LearningPathDetail';
export { Positionnement } from './Positionnement';
export { Recherche } from './Recherche';
export { Billing } from './Billing';
export { SubscriptionPayment } from './SubscriptionPayment';
export { VerifyEmail } from './VerifyEmail';
export { MagicLink } from './MagicLink';
export { Coaching } from './Coaching';
export { Collaboration } from './Collaboration';
export { PagesIndex } from './PagesIndex';
export { Login } from './Login';
export { Signup } from './Signup';
export { ForgotPassword } from './ForgotPassword';
export { Notifications } from './Notifications';
export { Messages } from './Messages';
export { Leaderboard } from './Leaderboard';
export { Veille } from './Veille';
export { Journal } from './Journal';
export { ArticleDetail } from './ArticleDetail';
export { Dossier } from './Dossier';
export { VideoTutorial } from './VideoTutorial';
export { VideoReels } from './VideoReels';
export { Magazine } from './Magazine';
export { MagazineArticle } from './MagazineArticle';
export { WeeklyNewsletter } from './WeeklyNewsletter';
export { WeeklyNewsDetail } from './WeeklyNewsDetail';
export { Newsletter } from './Newsletter';
export { Project } from './Project';
export { LearningSpace } from './LearningSpace';
export { Onboarding } from './Onboarding';
export { CoachingBookingFlow } from './CoachingBookingFlow';
export { PreCoachingQuestionnaire } from './PreCoachingQuestionnaire';
export { PreCoachingQuestionnaireResponse } from './PreCoachingQuestionnaireResponse';
export { JournalDetail } from './JournalDetail';
export { JournalNewEntry } from './JournalNewEntry';
export { JournalFreeEntry } from './JournalFreeEntry';
export { ResetPassword } from './ResetPassword';
export { Account } from './Account';
export { Error404 } from './Error404';
export { Error500 } from './Error500';
export { Help } from './Help';
export { Enterprise } from './Enterprise';
export { CourseDetail } from './CourseDetail';
export { LessonPlayer } from './LessonPlayer';
export { AstucesViewer } from './AstucesViewer';
export { ComplementaryContentViewer } from './ComplementaryContentViewer';
export { FlashcardsViewer } from './FlashcardsViewer';
export { VideoViewer } from './VideoViewer';
export { CoachingCompteRendu } from './CoachingCompteRendu';
// Phase 11 — Sitemap Alignment & MVP
export { default as Passeport } from './Passeport';
export { default as Gamification } from './Gamification';
export { default as CoachDashboard } from './CoachDashboard';
export { default as ManagerEnterprise } from './ManagerEnterprise';
export { default as ManagerCohort } from './ManagerCohort';
// Phase 12 — MVP P0 pages
export { default as PasseportCompetenceDetail } from './PasseportCompetenceDetail';
export { default as PasseportObjectifs } from './PasseportObjectifs';
export { default as CoachHeatmap } from './CoachHeatmap';
export { default as OnboardingSuccess } from './OnboardingSuccess';
export { default as OnboardingTutorial } from './OnboardingTutorial';
export { default as CoachingSessionDetail } from './CoachingSessionDetail';
export { default as CoachingCorrections } from './CoachingCorrections';
export { default as CoachCorrectionsQueue } from './CoachCorrectionsQueue';
export { default as CoachCorrectionInterface } from './CoachCorrectionInterface';
export { default as CoachApprenants } from './CoachApprenants';
export { default as BadgeDetail } from './BadgeDetail';
export { default as ProfileBadgesCompetences } from './ProfileBadgesCompetences';
export { default as ManagerAlerts } from './ManagerAlerts';
export { default as ManagerExport } from './ManagerExport';
export { default as DashboardCompetenceDetail } from './DashboardCompetenceDetail';
export { default as CoachTeamDashboard } from './CoachTeamDashboard';
export { default as FicheApprenantAnalytics } from './FicheApprenantAnalytics';
export { default as ProfilePrivacy } from './ProfilePrivacy';
export { default as EnterpriseAnalyticsDashboard } from './EnterpriseAnalyticsDashboard';
// Phase 13 — Remaining MVP P0 pages
export { default as PasseportRoadmap } from './PasseportRoadmap';
export { default as PasseportJac } from './PasseportJac';
export { default as CoachAnalytics } from './CoachAnalytics';
export { default as EnterpriseKpis } from './EnterpriseKpis';
export { default as ProfileConsent } from './ProfileConsent';
export { default as AlerteInactivite } from './AlerteInactivite';
export { default as AlerteStagnation } from './AlerteStagnation';
// Phase 14 — Ateliers + Masterclass + Événements
export { default as AtelierHub } from './AtelierHub';
export { default as AtelierDetail } from './AtelierDetail';
export { default as AtelierLive } from './AtelierLive';
export { default as AtelierPresentiel } from './AtelierPresentiel';
export { default as AtelierRecap } from './AtelierRecap';
export { default as AtelierWaitlist } from './AtelierWaitlist';
export { default as MasterclassHub } from './MasterclassHub';
export { default as MasterclassDetail } from './MasterclassDetail';
export { default as MasterclassLive } from './MasterclassLive';
export { default as MasterclassReplay } from './MasterclassReplay';
export { default as MasterclassSurvey } from './MasterclassSurvey';
export { default as EvenementHub } from './EvenementHub';
export { default as EvenementDetail } from './EvenementDetail';
export { default as EvenementLive } from './EvenementLive';
export { default as EvenementRecap } from './EvenementRecap';
// Phase 15 — Help + Coach + Project + Gamification + Dashboard
export { default as HelpArticle } from './HelpArticle';
export { default as HelpSearch } from './HelpSearch';
export { default as HelpTicketDetail } from './HelpTicketDetail';
export { default as HelpTicketNew } from './HelpTicketNew';
export { default as HelpTickets } from './HelpTickets';
export { default as HelpTutorialStep } from './HelpTutorialStep';
export { default as HelpTutorials } from './HelpTutorials';
export { default as CoachJournal } from './CoachJournal';
export { default as CoachJournalDetail } from './CoachJournalDetail';
export { default as CoachLearnerProfile } from './CoachLearnerProfile';
export { default as ProjectJac } from './ProjectJac';
export { default as ProjectPasseportFeed } from './ProjectPasseportFeed';
export { default as ProjectSkillGaps } from './ProjectSkillGaps';
export { default as ProjectTask } from './ProjectTask';
export { default as ProjectTeam } from './ProjectTeam';
export { default as BadgeGallery } from './BadgeGallery';
export { default as XPDashboard } from './XPDashboard';
export { default as DashboardAchievements } from './DashboardAchievements';
export { default as NotificationPreferences } from './NotificationPreferences';
// Phase 16 — 17 sitemap gap pages (P0 + P1 from FO_SCREENS_CONSOLIDATION)
export { default as PerplexityContentDetail } from './PerplexityContentDetail';
export { default as OnboardingQuestionnaire } from './OnboardingQuestionnaire';
export { default as CorrectionDetailLearner } from './CorrectionDetailLearner';
export { default as MessagingThread } from './MessagingThread';
export { default as CoachCalendar } from './CoachCalendar';
export { default as ApiDocs } from './ApiDocs';
export { default as ProjectsList } from './ProjectsList';
export { default as ItemRecommendations } from './ItemRecommendations';
export { default as PasseportHistorique } from './PasseportHistorique';
export { default as PurchaseCredits } from './PurchaseCredits';
export { default as StreakDetail } from './StreakDetail';
export { default as CoachEngagement } from './CoachEngagement';
export { default as CoachEnterpriseDashboard } from './CoachEnterpriseDashboard';
export { default as ManagerViewsBuilder } from './ManagerViewsBuilder';
export { default as JournalSearch } from './JournalSearch';
export { default as PrivacyDsar } from './PrivacyDsar';
export { default as PrivacyDeleteAccount } from './PrivacyDeleteAccount';
